version: '3.5'

services:
  check:
    image: digitpeak/dpdocker-cli
    command: /usr/src/Projects/DPDocker/code/scripts/exec-check.sh ${EXTENSION} ${FILE}
    volumes:
      - ../..:/usr/src/Projects

  fix:
    image: digitpeak/dpdocker-cli
    command: /usr/src/Projects/DPDocker/code/scripts/exec-fix.sh ${EXTENSION} ${FILE}
    volumes:
      - ../..:/usr/src/Projects

  analyze:
    image: digitpeak/dpdocker-cli
    command: /usr/src/Projects/DPDocker/code/scripts/exec-analyze.sh ${EXTENSION} ${FILE}
    volumes:
      - ../..:/usr/src/Projects
      - ./tmp/cache/rector:/tmp/rector
      - ./tmp/cache/phpstan:/tmp/phpstan
