version: '3.5'

services:
  web:
    image: digitpeak/dpdocker-web:${PHP_VERSION}
    environment:
      STARTUP_COMMAND_1: sudo chown docker:docker /home/docker && cp /var/www/html/Projects/DPDocker/webserver/scripts/index.php /var/www/html
      STARTUP_COMMAND_2: php /var/www/html/Projects/DPDocker/webserver/scripts/setup-joomla-site.php j3 all ${DB} 3 ${REBUILD}
      STARTUP_COMMAND_3: php /var/www/html/Projects/DPDocker/webserver/scripts/setup-joomla-site.php j4 all ${DB} 4 ${REBUILD}
      STARTUP_COMMAND_4: php /var/www/html/Projects/DPDocker/webserver/scripts/setup-joomla-site.php dev3 all ${DB} 3 ${REBUILD}
      STARTUP_COMMAND_5: php /var/www/html/Projects/DPDocker/webserver/scripts/setup-joomla-site.php dev4 all ${DB} 4 ${REBUILD}
      STARTUP_COMMAND_6: php /var/www/html/Projects/DPDocker/webserver/scripts/setup-joomla-site.php play3 '' ${DB} 3 ${REBUILD}
      STARTUP_COMMAND_7: php /var/www/html/Projects/DPDocker/webserver/scripts/setup-joomla-site.php play4 '' ${DB} 4 ${REBUILD}
      STARTUP_COMMAND_8: /var/www/html/Projects/DPDocker/webserver/scripts/setup-joomla-core.sh cms4 ${DB} ${REBUILD}
      STARTUP_COMMAND_9: /var/www/html/Projects/DPDocker/webserver/scripts/setup-joomla-core.sh cms5 ${DB} ${REBUILD}
      PHP_INI_XDEBUG__DISCOVER_CLIENT_HOST: 1
    depends_on:
      - mysql
      - postgres
      - mailcatcher
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/var/www/html
      - ../..:/var/www/html/Projects
      - ../..:/usr/src/Projects
    extra_hosts:
      - host.docker.internal:host-gateway

  mysql:
    image: mysql:${MYSQL_DBVERSION}
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    volumes:
      - ./mysql_${MYSQL_DBVERSION}_data:/var/lib/mysql

  postgres:
    image: postgres:${POSTGRES_DBVERSION}
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5432:5432
    volumes:
      - ./postgres_${POSTGRES_DBVERSION}_data:/var/lib/postgresql/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 999M
    depends_on:
      - mysql
    ports:
      - 81:80

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - postgres
    ports:
      - 82:80

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 83:1080

  ftpserver:
    image: stilliard/pure-ftpd
    environment:
      PUBLICHOST: localhost
      FTP_USER_NAME: ftp
      FTP_USER_PASS: ftp
      FTP_USER_HOME: /home/ftp
    ports:
      - 21:21
      - 30000-30009:30000-30009
    volumes:
      - ./www:/home/ftp
