version: '3.5'

services:
  web:
    image: dpdocker-web
    environment:
      STARTUP_COMMAND_1: cp /var/www/html/Projects/DPDocker/webserver/scripts/index.php /var/www/html
      STARTUP_COMMAND_2: php /var/www/html/Projects/DPDocker/webserver/scripts/setup-joomla-site.php j3 all ${DB} ${REBUILD}
      STARTUP_COMMAND_3: php /var/www/html/Projects/DPDocker/webserver/scripts/setup-joomla-site.php j4 all ${DB} ${REBUILD}
      STARTUP_COMMAND_4: php /var/www/html/Projects/DPDocker/webserver/scripts/setup-joomla-site.php dev3 all ${DB} ${REBUILD}
      STARTUP_COMMAND_5: php /var/www/html/Projects/DPDocker/webserver/scripts/setup-joomla-site.php dev4 all ${DB} ${REBUILD}
      STARTUP_COMMAND_6: php /var/www/html/Projects/DPDocker/webserver/scripts/setup-joomla-site.php play3 '' ${DB} ${REBUILD}
      STARTUP_COMMAND_7: php /var/www/html/Projects/DPDocker/webserver/scripts/setup-joomla-site.php play4 '' ${DB} ${REBUILD}
      STARTUP_COMMAND_8: /var/www/html/Projects/DPDocker/webserver/scripts/setup-joomla-core.sh cms3 ${DB} ${REBUILD}
      STARTUP_COMMAND_9: /var/www/html/Projects/DPDocker/webserver/scripts/setup-joomla-core.sh cms4 ${DB} ${REBUILD}
    links:
      - mysql:mysql
      - postgres:postgres
      - mailcatcher:mailcatcher
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/var/www/html
      - ../..:/var/www/html/Projects
      - ../..:/usr/src/Projects

  mysql:
    image: mysql:${DBVERSION}
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_data:/var/lib/mysql

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    links:
      - mysql
    ports:
      - 81:80

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root
    links:
      - postgres
    ports:
      - 82:80

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 83:1080
