services:
  joomla-pr:
    image: digitpeak/dpdocker-web:${PHP_VERSION}
    environment:
      STARTUP_COMMAND_1: sudo chown docker:docker /home/docker
      STARTUP_COMMAND_2: /var/www/html/Projects/DPDocker/joomla-pr/scripts/exec-joomla-pr-webserver.sh ${PR} ${DB} ${REBUILD}
      JOOMLA_INSTALLATION_DISABLE_LOCALHOST_CHECK: 1
    depends_on:
      - mysql-pr
      - postgres-pr
      - phpmyadmin-pr
      - pgadmin-pr
      - mailcatcher-pr
      - ftpserver-pr
    ports:
      - 8090:80
    volumes:
      - ./www:/var/www/html
      - ../..:/var/www/html/Projects

  mysql-pr:
    image: mysql:${MYSQL_DBVERSION}
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password --log_error_suppression_list=MY-013360 --skip-log-bin
    volumes:
      - ./mysql_data:/var/lib/mysql

  postgres-pr:
    image: postgres:${POSTGRES_DBVERSION}
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  phpmyadmin-pr:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql-pr
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql-pr
    ports:
      - 8091:80

  pgadmin-pr:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - postgres-pr
    ports:
      - 8092:80

  mailcatcher-pr:
    image: schickling/mailcatcher
    ports:
      - 8093:1080

  ftpserver-pr:
    image: stilliard/pure-ftpd
    environment:
      PUBLICHOST: localhost
      FTP_USER_NAME: ftp
      FTP_USER_PASS: ftp
      FTP_USER_HOME: /home/ftp
    ports:
      - 121:21
    volumes:
      - ./www:/home/ftp
