services:
  install:
    image: digitpeak/dpdocker-cli
    command: /usr/src/Projects/DPDocker/composer/scripts/exec-install.sh ${EXTENSION} ${EXTENSION_FOLDER}
    volumes:
      - ../..:/usr/src/Projects

  update:
    image: digitpeak/dpdocker-cli
    command: /usr/src/Projects/DPDocker/composer/scripts/exec-update.sh ${EXTENSION} ${EXTENSION_FOLDER}
    volumes:
      - ../..:/usr/src/Projects

  dep-tree:
    image: digitpeak/dpdocker-cli
    command: /usr/src/Projects/DPDocker/composer/scripts/exec-dep-tree.sh ${EXTENSION} ${EXTENSION_FOLDER}
    volumes:
      - ../..:/usr/src/Projects

  list:
    image: digitpeak/dpdocker-cli
    command: /usr/src/Projects/DPDocker/composer/scripts/exec-list.sh ${EXTENSION} ${EXTENSION_FOLDER}
    volumes:
      - ../..:/usr/src/Projects
